import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:prometh_ai/state/warning.dart';
import 'package:prometh_ai/widget/aclose_button.dart';
import 'package:prometh_ai/widget/theme_selectors.dart';

import '../../theme.dart';
import 'link_button.dart';

const _warningText =
    "Please note that the content provided in this app, including nutritional information and health advice, is generated by an AI algorithm based on data found in various nutritional books and resources.\n\n"
    "It is intended to be used as a general guide only and should not be relied upon as personalized health or nutritional advice.\n\n"
    "It is always recommended to consult with a registered dietitian, nutritionist, or a healthcare professional before making any major changes to your diet or health routine.\n\n"
    "The use of the information provided in this app is solely at your own risk.\n\n"
    "The literature used to train our algorithm includes:";

class WarningScreen extends HookConsumerWidget {
  const WarningScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final warningNotifier = ref.read(WarningNotifier.provider.notifier);
    return Scaffold(
      backgroundColor: Colors.black.withOpacity(0.8),
      body: SafeArea(
        child: Padding(
            padding: const EdgeInsets.only(left: 16, right: 16),
            child: Column(
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const SizedBox(width: 44),
                    const Icon(
                      Icons.warning_amber_outlined,
                      color: C.white,
                      size: 64,
                    ),
                    ACloseButton(onPressed: warningNotifier.hide, color: C.white),
                  ],
                ),
                const SizedBox(height: 32),
                ListView(
                  shrinkWrap: true,
                  children: [
                    Text(_warningText, style: tt(context).titleMedium!.copyWith(color: C.white)),
                    const SizedBox(height: 16),
                    const LinkButton(
                        "1. University of Hawai‘i at Mānoa Food Science and Human Nutrition Program. (2020). Human Nutrition: 2020 Edition.",
                        link: "http://pressbooks.oer.hawaii.edu/humannutrition2/"),
                    const SizedBox(height: 16),
                    const LinkButton("2. Lindshield, B. (2018). Kansas State University Human Nutrition Flexbook.",
                        link: "https://open.umn.edu/opentextbooks/textbooks/kansas-state-university-human-nutrition-flexbook"),
                  ],
                ),
              ],
            )),
      ),
    );
  }
}
